default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: aoom_academy_quest_development
  username: aueaarri
  password: jm131038                
  host: 127.0.0.1
  port: 5432

  

test:
  <<: *default
  database: aoom_academy_quest_test


production:
  primary: &primary_production
    <<: *default
    database: aoom_academy_quest_production
    username: aoom_academy_quest
    password: <%= ENV["AOOM_ACADEMY_QUEST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: aoom_academy_quest_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: aoom_academy_quest_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: aoom_academy_quest_production_cable
    migrations_paths: db/cable_migrate